#!/usr/bin/env bash
# Install Nginx

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello world" > /etc/nginx/html/index.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;

     location /redirect_me {
     	 return 301 http://facebook.com/;
     }
}
" > /etc/nginx/sites-available/default
service nginx restart
