#!/usr/bin/env bash                                                                                                                                                    
# Bash scripts that kill 4-to_infinty_and_beyond                                                                                                                       
pkill  -f 4-to_infinity_and_beyond
