#!/usr/bin/env bash
# Displays numbers from 1 to 20 with a certain pattern
four="bad luck from China"
nine="bad luck from Japan"
seventeen="bad luck from Italy"
i=1
while [ $i -lt 21 ]
do
	case $i in
		4) echo "$i"
			echo "$four";;
		9) echo "$i"
			echo "$nine";;
		17) echo "$i"
			echo "$seventeen";;
		*) echo "$i";;
	esac
	i=$((i+1))
done
